# -*- coding: utf-8 -*-
"""weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JGx_oZWyxyAx_uyXgUnXz5UAe-INhda
"""

# Nirmani Jayaprabha Pathiranage
# nirma2015@gmail.com
# +94712233126

### PYTHON AND CYBER SECURITY BOOTCAMP SHAPEAI PROJECT ###

# import necessary dependencies

import requests
from datetime import datetime

# define the api key from OpenWeatherMap API
api_key = '7cb9de382f045f079a0ad722fa1c5c74'

# input name of the location by user, where the weather details needed to be searched
location = input("Enter the city name: ")

# define the complete api link
complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key

# get the request from the above api link
api_link = requests.get(complete_api_link)

# get data obtained from the api in json format
api_data = api_link.json()

#create variables to store and display data

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

# print the output in the console
print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

### TASK ###

# Log the obtained weather data to a text file called "output.txt"
# Write the lines to the file

with open('output.txt', 'w') as writefile:
    print ("-------------------------------------------------------------", file=writefile)
    print ("Weather Stats for - {}  || {}".format(location.upper(), date_time), file=writefile)
    print ("-------------------------------------------------------------", file=writefile)

    print ("Current temperature is: {:.2f} deg C".format(temp_city), file=writefile)
    print ("Current weather desc  :", weather_desc, file=writefile)
    print ("Current Humidity      :", hmdt, '%', file=writefile)
    print ("Current wind speed    :", wind_spd , 'kmph', file=writefile)

# Verify if the appending is successfully executed

with open('output.txt', 'r') as readfile:
    print(readfile.read())